import type { Metadata } from "next";
import { Geist_Mono, Source_Serif_4, Zalando_Sans } from "next/font/google";
import "./globals.css";

const zalandoSans = Zalando_Sans({
  variable: "--font-zalando-sans",
  weight: "variable",
  subsets: ["latin"],
});

const sourceserif = Source_Serif_4({
  variable: "--font-source-serif-4",
  weight: "variable",
  subsets: ["latin"],
});

const geistmono = Geist_Mono({
  variable: "--font-geist-mono",
  weight: "variable",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${zalandoSans.variable} ${geistmono.variable} ${sourceserif.variable} antialiased`}
      >
        {/* <NavMenu /> */}
        {children}
      </body>
    </html>
  );
}
