import { Span } from "./types";

export const dummySpans: Span[] = [
  {
    span_id: 1,
    trace_id: 101,
    parent_span_ids: null,
    start_time: new Date("2025-11-11T10:00:00"),
    end_time: new Date("2025-11-11T10:00:02"),
    duration: 2.0,
    input_preview:
      "Analyze user query: What are the best practices for building scalable web applications?",
    input_blob_url: "https://storage.example.com/inputs/span-1",
    output_preview:
      "Query identified as technical question. Breaking down into subtasks: architecture patterns, database design, caching strategies...",
    output_blob_url: "https://storage.example.com/outputs/span-1",
    llm_model: "gpt-4-turbo",
    prompt_tokens: 150,
    completion_tokens: 75,
    cost: 0.0045,
    status: "completed",
    error_message: null,
  },
  {
    span_id: 2,
    trace_id: 101,
    parent_span_ids: [1],
    start_time: new Date("2025-11-11T10:00:03"),
    end_time: new Date("2025-11-11T10:00:05"),
    duration: 1.8,
    input_preview:
      "Research architecture patterns for scalable applications...",
    input_blob_url: "https://storage.example.com/inputs/span-2",
    output_preview:
      "Found patterns: Microservices, Event-driven architecture, CQRS, Serverless...",
    output_blob_url: "https://storage.example.com/outputs/span-2",
    llm_model: "gpt-3.5-turbo",
    prompt_tokens: 120,
    completion_tokens: 90,
    cost: 0.0021,
    status: "completed",
    error_message: null,
  },
  {
    span_id: 3,
    trace_id: 101,
    parent_span_ids: [1],
    start_time: new Date("2025-11-11T10:00:03"),
    end_time: new Date("2025-11-11T10:00:04"),
    duration: 1.2,
    input_preview: "Research database design best practices for scalability...",
    input_blob_url: "https://storage.example.com/inputs/span-3",
    output_preview:
      "Key strategies: Sharding, Read replicas, Connection pooling, Indexing optimization...",
    output_blob_url: "https://storage.example.com/outputs/span-3",
    llm_model: "gpt-4-turbo",
    prompt_tokens: 110,
    completion_tokens: 85,
    cost: 0.0038,
    status: "completed",
    error_message: null,
  },
  {
    span_id: 4,
    trace_id: 101,
    parent_span_ids: [2, 3],
    start_time: new Date("2025-11-11T10:00:06"),
    end_time: new Date("2025-11-11T10:00:08"),
    duration: 2.1,
    input_preview:
      "Synthesize findings from architecture and database research into cohesive recommendations...",
    input_blob_url: "https://storage.example.com/inputs/span-4",
    output_preview:
      "Recommended approach: Start with microservices architecture, use PostgreSQL with read replicas, implement Redis caching...",
    output_blob_url: "https://storage.example.com/outputs/span-4",
    llm_model: "gpt-4-turbo",
    prompt_tokens: 280,
    completion_tokens: 150,
    cost: 0.0092,
    status: "completed",
    error_message: null,
  },
  {
    span_id: 5,
    trace_id: 101,
    parent_span_ids: [1],
    start_time: new Date("2025-11-11T10:00:03"),
    end_time: new Date("2025-11-11T10:00:04"),
    duration: 1.0,
    input_preview: "Find relevant code examples and documentation...",
    input_blob_url: "https://storage.example.com/inputs/span-5",
    output_preview:
      "Retrieved examples from GitHub and official documentation sources...",
    output_blob_url: "https://storage.example.com/outputs/span-5",
    llm_model: "gpt-3.5-turbo",
    prompt_tokens: 90,
    completion_tokens: 60,
    cost: 0.0015,
    status: "completed",
    error_message: null,
  },
  {
    span_id: 6,
    trace_id: 101,
    parent_span_ids: [4, 5],
    start_time: new Date("2025-11-11T10:00:09"),
    end_time: new Date("2025-11-11T10:00:11"),
    duration: 2.5,
    input_preview:
      "Generate final response with recommendations and code examples...",
    input_blob_url: "https://storage.example.com/inputs/span-6",
    output_preview:
      "Here are the best practices for building scalable web applications: 1. Architecture: Use microservices...",
    output_blob_url: "https://storage.example.com/outputs/span-6",
    llm_model: "gpt-4-turbo",
    prompt_tokens: 420,
    completion_tokens: 300,
    cost: 0.0156,
    status: "completed",
    error_message: null,
  },
];
