import { Agent, Trace, Span } from "./types";

export const dummyAgents: Agent[] = [
  {
    agent_id: "agent-1",
    name: "Research Assistant",
    user_id: 1,
    description: "Specialized in gathering and synthesizing information",
  },
  {
    agent_id: "agent-2",
    name: "Code Generator",
    user_id: 1,
    description: "Generates production-ready code from specifications",
  },
  {
    agent_id: "agent-3",
    name: "Data Analyzer",
    user_id: 2,
    description: "Analyzes and visualizes complex datasets",
  },
];

export const dummyTraces: Trace[] = [
  {
    trace_id: 101,
    agent_id: "agent-1",
    start_time: new Date("2025-11-11T10:00:00"),
    end_time: new Date("2025-11-11T10:00:11"),
    duration: 11.0,
    total_cost: 0.0367,
    total_tokens: 1265,
    status: "completed",
    user_id: 1,
  },
  {
    trace_id: 102,
    agent_id: "agent-1",
    start_time: new Date("2025-11-11T11:30:00"),
    end_time: new Date("2025-11-11T11:30:08"),
    duration: 8.0,
    total_cost: 0.0245,
    total_tokens: 890,
    status: "completed",
    user_id: 1,
  },
  {
    trace_id: 103,
    agent_id: "agent-1",
    start_time: new Date("2025-11-11T14:15:00"),
    end_time: new Date("2025-11-11T14:15:06"),
    duration: 6.5,
    total_cost: 0.0198,
    total_tokens: 720,
    status: "failed",
    user_id: 1,
  },
  {
    trace_id: 201,
    agent_id: "agent-2",
    start_time: new Date("2025-11-11T09:20:00"),
    end_time: new Date("2025-11-11T09:20:15"),
    duration: 15.0,
    total_cost: 0.0512,
    total_tokens: 1840,
    status: "completed",
    user_id: 1,
  },
  {
    trace_id: 202,
    agent_id: "agent-2",
    start_time: new Date("2025-11-11T13:45:00"),
    end_time: new Date("2025-11-11T13:45:12"),
    duration: 12.0,
    total_cost: 0.0423,
    total_tokens: 1520,
    status: "completed",
    user_id: 1,
  },
  {
    trace_id: 301,
    agent_id: "agent-3",
    start_time: new Date("2025-11-11T10:10:00"),
    end_time: new Date("2025-11-11T10:10:18"),
    duration: 18.0,
    total_cost: 0.0634,
    total_tokens: 2280,
    status: "completed",
    user_id: 2,
  },
  {
    trace_id: 302,
    agent_id: "agent-3",
    start_time: new Date("2025-11-11T15:30:00"),
    end_time: new Date("2025-11-11T15:30:09"),
    duration: 9.0,
    total_cost: 0.0312,
    total_tokens: 1120,
    status: "failed",
    user_id: 2,
  },
  {
    trace_id: 303,
    agent_id: "agent-3",
    start_time: new Date("2025-11-11T16:00:00"),
    end_time: new Date("2025-11-11T16:00:07"),
    duration: 7.0,
    total_cost: 0.0267,
    total_tokens: 960,
    status: "completed",
    user_id: 2,
  },
];

export const dummySpans: Span[] = [
  {
    span_id: 1,
    trace_id: 101,
    parent_span_ids: null,
    start_time: new Date("2025-11-11T10:00:00"),
    end_time: new Date("2025-11-11T10:00:02"),
    duration: 2.0,
    input_preview:
      "Analyze user query: What are the best practices for building scalable web applications?",
    input_blob_url: "https://storage.example.com/inputs/span-1",
    output_preview:
      "Query identified as technical question. Breaking down into subtasks: architecture patterns, database design, caching strategies...",
    output_blob_url: "https://storage.example.com/outputs/span-1",
    llm_model: "gpt-4-turbo",
    prompt_tokens: 150,
    completion_tokens: 75,
    cost: 0.0045,
    status: "completed",
    error_message: null,
  },
  {
    span_id: 2,
    trace_id: 101,
    parent_span_ids: [1],
    start_time: new Date("2025-11-11T10:00:03"),
    end_time: new Date("2025-11-11T10:00:05"),
    duration: 1.8,
    input_preview:
      "Research architecture patterns for scalable applications...",
    input_blob_url: "https://storage.example.com/inputs/span-2",
    output_preview:
      "Found patterns: Microservices, Event-driven architecture, CQRS, Serverless...",
    output_blob_url: "https://storage.example.com/outputs/span-2",
    llm_model: "gpt-3.5-turbo",
    prompt_tokens: 120,
    completion_tokens: 90,
    cost: 0.0021,
    status: "completed",
    error_message: null,
  },
  {
    span_id: 3,
    trace_id: 101,
    parent_span_ids: [1],
    start_time: new Date("2025-11-11T10:00:03"),
    end_time: new Date("2025-11-11T10:00:04"),
    duration: 1.2,
    input_preview: "Research database design best practices for scalability...",
    input_blob_url: "https://storage.example.com/inputs/span-3",
    output_preview:
      "Key strategies: Sharding, Read replicas, Connection pooling, Indexing optimization...",
    output_blob_url: "https://storage.example.com/outputs/span-3",
    llm_model: "gpt-4-turbo",
    prompt_tokens: 110,
    completion_tokens: 85,
    cost: 0.0038,
    status: "completed",
    error_message: null,
  },
  {
    span_id: 4,
    trace_id: 101,
    parent_span_ids: [2, 3],
    start_time: new Date("2025-11-11T10:00:06"),
    end_time: new Date("2025-11-11T10:00:08"),
    duration: 2.1,
    input_preview:
      "Synthesize findings from architecture and database research into cohesive recommendations...",
    input_blob_url: "https://storage.example.com/inputs/span-4",
    output_preview:
      "Recommended approach: Start with microservices architecture, use PostgreSQL with read replicas, implement Redis caching...",
    output_blob_url: "https://storage.example.com/outputs/span-4",
    llm_model: "gpt-4-turbo",
    prompt_tokens: 280,
    completion_tokens: 150,
    cost: 0.0092,
    status: "completed",
    error_message: null,
  },
  {
    span_id: 5,
    trace_id: 101,
    parent_span_ids: [1],
    start_time: new Date("2025-11-11T10:00:03"),
    end_time: new Date("2025-11-11T10:00:04"),
    duration: 1.0,
    input_preview: "Find relevant code examples and documentation...",
    input_blob_url: "https://storage.example.com/inputs/span-5",
    output_preview:
      "Retrieved examples from GitHub and official documentation sources...",
    output_blob_url: "https://storage.example.com/outputs/span-5",
    llm_model: "gpt-3.5-turbo",
    prompt_tokens: 90,
    completion_tokens: 60,
    cost: 0.0015,
    status: "completed",
    error_message: null,
  },
  {
    span_id: 6,
    trace_id: 101,
    parent_span_ids: [4, 5],
    start_time: new Date("2025-11-11T10:00:09"),
    end_time: new Date("2025-11-11T10:00:11"),
    duration: 2.5,
    input_preview:
      "Generate final response with recommendations and code examples...",
    input_blob_url: "https://storage.example.com/inputs/span-6",
    output_preview:
      "Here are the best practices for building scalable web applications: 1. Architecture: Use microservices...",
    output_blob_url: "https://storage.example.com/outputs/span-6",
    llm_model: "gpt-4-turbo",
    prompt_tokens: 420,
    completion_tokens: 300,
    cost: 0.0156,
    status: "completed",
    error_message: null,
  },
  // Trace 102 spans
  {
    span_id: 7,
    trace_id: 102,
    parent_span_ids: null,
    start_time: new Date("2025-11-11T11:30:00"),
    end_time: new Date("2025-11-11T11:30:03"),
    duration: 3.0,
    input_preview: "Research latest trends in AI and machine learning...",
    input_blob_url: "https://storage.example.com/inputs/span-7",
    output_preview:
      "Current trends: Large language models, multimodal AI, AI safety, federated learning...",
    output_blob_url: "https://storage.example.com/outputs/span-7",
    llm_model: "gpt-4-turbo",
    prompt_tokens: 180,
    completion_tokens: 120,
    cost: 0.0054,
    status: "completed",
    error_message: null,
  },
  {
    span_id: 8,
    trace_id: 102,
    parent_span_ids: [7],
    start_time: new Date("2025-11-11T11:30:04"),
    end_time: new Date("2025-11-11T11:30:08"),
    duration: 4.0,
    input_preview: "Compile comprehensive report on AI trends...",
    input_blob_url: "https://storage.example.com/inputs/span-8",
    output_preview:
      "Report complete with sections on LLMs, ethical considerations, industry applications...",
    output_blob_url: "https://storage.example.com/outputs/span-8",
    llm_model: "gpt-4-turbo",
    prompt_tokens: 320,
    completion_tokens: 180,
    cost: 0.0191,
    status: "completed",
    error_message: null,
  },
  // Trace 103 spans (failed trace)
  {
    span_id: 9,
    trace_id: 103,
    parent_span_ids: null,
    start_time: new Date("2025-11-11T14:15:00"),
    end_time: new Date("2025-11-11T14:15:02"),
    duration: 2.0,
    input_preview: "Analyze financial data for Q4 projections...",
    input_blob_url: "https://storage.example.com/inputs/span-9",
    output_preview: "Processing financial data...",
    output_blob_url: "https://storage.example.com/outputs/span-9",
    llm_model: "gpt-3.5-turbo",
    prompt_tokens: 200,
    completion_tokens: 50,
    cost: 0.003,
    status: "completed",
    error_message: null,
  },
  {
    span_id: 10,
    trace_id: 103,
    parent_span_ids: [9],
    start_time: new Date("2025-11-11T14:15:03"),
    end_time: new Date("2025-11-11T14:15:06"),
    duration: 3.0,
    input_preview: "Generate financial projections and analysis...",
    input_blob_url: "https://storage.example.com/inputs/span-10",
    output_preview: null,
    output_blob_url: null,
    llm_model: "gpt-4-turbo",
    prompt_tokens: 280,
    completion_tokens: 0,
    cost: 0.0168,
    status: "failed",
    error_message: "API rate limit exceeded. Please try again later.",
  },
  // Trace 201 spans
  {
    span_id: 11,
    trace_id: 201,
    parent_span_ids: null,
    start_time: new Date("2025-11-11T09:20:00"),
    end_time: new Date("2025-11-11T09:20:04"),
    duration: 4.0,
    input_preview: "Parse technical specifications for API endpoints...",
    input_blob_url: "https://storage.example.com/inputs/span-11",
    output_preview:
      "Identified 5 REST endpoints with authentication requirements...",
    output_blob_url: "https://storage.example.com/outputs/span-11",
    llm_model: "gpt-4-turbo",
    prompt_tokens: 220,
    completion_tokens: 150,
    cost: 0.0077,
    status: "completed",
    error_message: null,
  },
  {
    span_id: 12,
    trace_id: 201,
    parent_span_ids: [11],
    start_time: new Date("2025-11-11T09:20:05"),
    end_time: new Date("2025-11-11T09:20:09"),
    duration: 4.0,
    input_preview: "Generate TypeScript interfaces for API types...",
    input_blob_url: "https://storage.example.com/inputs/span-12",
    output_preview:
      "export interface User { id: string; name: string; email: string; }...",
    output_blob_url: "https://storage.example.com/outputs/span-12",
    llm_model: "gpt-4-turbo",
    prompt_tokens: 180,
    completion_tokens: 200,
    cost: 0.0092,
    status: "completed",
    error_message: null,
  },
  {
    span_id: 13,
    trace_id: 201,
    parent_span_ids: [11],
    start_time: new Date("2025-11-11T09:20:05"),
    end_time: new Date("2025-11-11T09:20:10"),
    duration: 5.0,
    input_preview: "Generate API client implementation code...",
    input_blob_url: "https://storage.example.com/inputs/span-13",
    output_preview:
      "class APIClient { constructor(baseURL: string) { this.baseURL = baseURL; }...",
    output_blob_url: "https://storage.example.com/outputs/span-13",
    llm_model: "gpt-4-turbo",
    prompt_tokens: 250,
    completion_tokens: 280,
    cost: 0.0146,
    status: "completed",
    error_message: null,
  },
  {
    span_id: 14,
    trace_id: 201,
    parent_span_ids: [12, 13],
    start_time: new Date("2025-11-11T09:20:11"),
    end_time: new Date("2025-11-11T09:20:15"),
    duration: 4.0,
    input_preview: "Generate comprehensive documentation and tests...",
    input_blob_url: "https://storage.example.com/inputs/span-14",
    output_preview:
      "# API Client Documentation\n\n## Installation\n```bash\nnpm install...",
    output_blob_url: "https://storage.example.com/outputs/span-14",
    llm_model: "gpt-4-turbo",
    prompt_tokens: 380,
    completion_tokens: 320,
    cost: 0.0197,
    status: "completed",
    error_message: null,
  },
  // Trace 202 spans
  {
    span_id: 15,
    trace_id: 202,
    parent_span_ids: null,
    start_time: new Date("2025-11-11T13:45:00"),
    end_time: new Date("2025-11-11T13:45:05"),
    duration: 5.0,
    input_preview: "Design database schema for e-commerce platform...",
    input_blob_url: "https://storage.example.com/inputs/span-15",
    output_preview:
      "Schema includes: users, products, orders, payments, inventory tables...",
    output_blob_url: "https://storage.example.com/outputs/span-15",
    llm_model: "gpt-4-turbo",
    prompt_tokens: 190,
    completion_tokens: 160,
    cost: 0.0085,
    status: "completed",
    error_message: null,
  },
  {
    span_id: 16,
    trace_id: 202,
    parent_span_ids: [15],
    start_time: new Date("2025-11-11T13:45:06"),
    end_time: new Date("2025-11-11T13:45:12"),
    duration: 6.0,
    input_preview: "Generate SQL migration files and ORM models...",
    input_blob_url: "https://storage.example.com/inputs/span-16",
    output_preview:
      "CREATE TABLE users (id SERIAL PRIMARY KEY, email VARCHAR(255)...",
    output_blob_url: "https://storage.example.com/outputs/span-16",
    llm_model: "gpt-4-turbo",
    prompt_tokens: 310,
    completion_tokens: 280,
    cost: 0.0338,
    status: "completed",
    error_message: null,
  },
  // Trace 301 spans
  {
    span_id: 17,
    trace_id: 301,
    parent_span_ids: null,
    start_time: new Date("2025-11-11T10:10:00"),
    end_time: new Date("2025-11-11T10:10:06"),
    duration: 6.0,
    input_preview: "Load and preprocess large dataset (2.5GB CSV)...",
    input_blob_url: "https://storage.example.com/inputs/span-17",
    output_preview:
      "Dataset loaded: 1.2M rows, 45 columns. Applied cleaning and normalization...",
    output_blob_url: "https://storage.example.com/outputs/span-17",
    llm_model: "gpt-4-turbo",
    prompt_tokens: 280,
    completion_tokens: 180,
    cost: 0.0109,
    status: "completed",
    error_message: null,
  },
  {
    span_id: 18,
    trace_id: 301,
    parent_span_ids: [17],
    start_time: new Date("2025-11-11T10:10:07"),
    end_time: new Date("2025-11-11T10:10:12"),
    duration: 5.0,
    input_preview: "Perform statistical analysis and detect outliers...",
    input_blob_url: "https://storage.example.com/inputs/span-18",
    output_preview:
      "Analysis complete: Mean=45.2, Std=12.8, Outliers detected: 342...",
    output_blob_url: "https://storage.example.com/outputs/span-18",
    llm_model: "gpt-4-turbo",
    prompt_tokens: 320,
    completion_tokens: 200,
    cost: 0.0138,
    status: "completed",
    error_message: null,
  },
  {
    span_id: 19,
    trace_id: 301,
    parent_span_ids: [18],
    start_time: new Date("2025-11-11T10:10:13"),
    end_time: new Date("2025-11-11T10:10:18"),
    duration: 5.0,
    input_preview: "Generate visualizations and insights report...",
    input_blob_url: "https://storage.example.com/inputs/span-19",
    output_preview:
      "Created 8 charts: distribution plots, correlation heatmap, time series...",
    output_blob_url: "https://storage.example.com/outputs/span-19",
    llm_model: "gpt-4-turbo",
    prompt_tokens: 420,
    completion_tokens: 340,
    cost: 0.0387,
    status: "completed",
    error_message: null,
  },
  // Trace 302 spans (failed trace)
  {
    span_id: 20,
    trace_id: 302,
    parent_span_ids: null,
    start_time: new Date("2025-11-11T15:30:00"),
    end_time: new Date("2025-11-11T15:30:04"),
    duration: 4.0,
    input_preview: "Extract features from image dataset...",
    input_blob_url: "https://storage.example.com/inputs/span-20",
    output_preview: "Processing 5000 images with ResNet-50...",
    output_blob_url: "https://storage.example.com/outputs/span-20",
    llm_model: "gpt-4-turbo",
    prompt_tokens: 150,
    completion_tokens: 80,
    cost: 0.0049,
    status: "completed",
    error_message: null,
  },
  {
    span_id: 21,
    trace_id: 302,
    parent_span_ids: [20],
    start_time: new Date("2025-11-11T15:30:05"),
    end_time: new Date("2025-11-11T15:30:09"),
    duration: 4.0,
    input_preview: "Train classification model on extracted features...",
    input_blob_url: "https://storage.example.com/inputs/span-21",
    output_preview: null,
    output_blob_url: null,
    llm_model: "gpt-4-turbo",
    prompt_tokens: 200,
    completion_tokens: 0,
    cost: 0.0263,
    status: "failed",
    error_message: "Model training failed: insufficient memory available.",
  },
  // Trace 303 spans
  {
    span_id: 22,
    trace_id: 303,
    parent_span_ids: null,
    start_time: new Date("2025-11-11T16:00:00"),
    end_time: new Date("2025-11-11T16:00:03"),
    duration: 3.0,
    input_preview: "Aggregate daily metrics from multiple data sources...",
    input_blob_url: "https://storage.example.com/inputs/span-22",
    output_preview:
      "Collected metrics from 12 sources: API calls, database queries, cache hits...",
    output_blob_url: "https://storage.example.com/outputs/span-22",
    llm_model: "gpt-3.5-turbo",
    prompt_tokens: 160,
    completion_tokens: 95,
    cost: 0.0031,
    status: "completed",
    error_message: null,
  },
  {
    span_id: 23,
    trace_id: 303,
    parent_span_ids: [22],
    start_time: new Date("2025-11-11T16:00:04"),
    end_time: new Date("2025-11-11T16:00:07"),
    duration: 3.0,
    input_preview: "Generate executive dashboard and KPI summary...",
    input_blob_url: "https://storage.example.com/inputs/span-23",
    output_preview:
      "Dashboard metrics: 99.8% uptime, 1.2M requests, avg response: 145ms...",
    output_blob_url: "https://storage.example.com/outputs/span-23",
    llm_model: "gpt-4-turbo",
    prompt_tokens: 240,
    completion_tokens: 160,
    cost: 0.0236,
    status: "completed",
    error_message: null,
  },
];
